"""Add columns to track views for each drop and how many views are allowed before it self destructs

Revision ID: 03d15b4ce406
Revises: 
Create Date: 2017-09-25 10:36:43.060000+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03d15b4ce406'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drops', sa.Column('self_destructs_in', sa.Integer(), nullable=True))
    op.add_column('drops', sa.Column('views', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('drops', 'views')
    op.drop_column('drops', 'self_destructs_in')
    # ### end Alembic commands ###
