"""Limit the drop's data column to 256 mb

Revision ID: f5fb2b81d12b
Revises: 03d15b4ce406
Create Date: 2017-11-09 21:31:18.807000+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5fb2b81d12b'
down_revision = '03d15b4ce406'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
    op.alter_column('drops', 'data', type_=sa.types.Text(268435456), existing_type=sa.types.Text(), existing_nullable=False, existing_server_default='')


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
    op.alter_column('drops', 'data', type_=sa.types.Text(), existing_nullable=False, existing_server_default='')
